"use client";

import { useState, use, useEffect, useCallback } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeftIcon, ArrowRightIcon, SparklesIcon } from "@heroicons/react/24/solid";

// ... (imports)

export default function AnnotationPage({ params }: { params: Promise<{ id: string, imageId: string }> }) {
    // ... (state)
    const [detecting, setDetecting] = useState(false);

    // ... (useEffect, etc.)

    const handleAutoDetect = async () => {
        setDetecting(true);
        try {
            const res = await fetch(`http://localhost:8000/projects/${id}/images/${imageId}/predict`, {
                method: "POST"
            });
            if (res.ok) {
                const newAnns = await res.json();
                // Merge with existing or replace? Let's apppend for now.
                // We should probably check for duplicates based on location/label or just let user decide.
                // Unique IDs are generated by backend: "auto-..."
                setAnnotations(prev => [...prev, ...newAnns]);
            }
        } catch (e) {
            console.error("Auto detect failed", e);
        } finally {
            setDetecting(false);
        }
    };

    // ... (render)

    return (
        <main className="h-screen flex flex-col bg-gray-950 text-white overflow-hidden">
            {/* Header */}
            <header className="h-14 border-b border-gray-800 flex items-center px-4 justify-between bg-gray-900 z-10">
                <div className="flex items-center gap-4">
                    {/* ... (navigation) ... */}
                    <div className="flex items-center gap-2">
                        {/* ... (arrows) ... */}
                    </div>
                </div>

                <div className="flex items-center gap-2 bg-gray-800 rounded p-1">
                    <button onClick={() => setTool("select")} className={`px-3 py-1 text-xs rounded ${tool === "select" ? "bg-blue-600 text-white" : "text-gray-400 hover:text-white"}`}>Select (V)</button>
                    <button onClick={() => setTool("pan")} className={`px-3 py-1 text-xs rounded ${tool === "pan" ? "bg-blue-600 text-white" : "text-gray-400 hover:text-white"}`}>Pan (H)</button>
                    <button onClick={() => setTool("rect")} className={`px-3 py-1 text-xs rounded ${tool === "rect" ? "bg-blue-600 text-white" : "text-gray-400 hover:text-white"}`}>Rectangle (R)</button>
                    <div className="w-px h-4 bg-gray-700 mx-2"></div>
                    <button
                        onClick={handleAutoDetect}
                        disabled={detecting}
                        className={`px-3 py-1 text-xs rounded flex items-center gap-1 ${detecting ? "bg-purple-900/50 text-purple-300" : "bg-purple-600 text-white hover:bg-purple-500"}`}
                    >
                        <SparklesIcon className="w-3 h-3" />
                        {detecting ? "Detecting..." : "Auto Detect"}
                    </button>
                </div>

                <div>
                    {/* ... (save status) ... */}
                </div>
            </header>

            <div className="flex-1 flex overflow-hidden">
                {/* Helper Sidebar */}
                <div className="w-16 border-r border-gray-800 bg-gray-900 flex flex-col items-center py-4 gap-4">
                    {/* Could add tool icons here */}
                </div>

                {/* Canvas */}
                <div className="flex-1 bg-black relative flex items-center justify-center overflow-hidden">
                    {imagePath && (
                        <AnnotationStage
                            imageSrc={imagePath}
                            annotations={annotations}
                            onAnnotationsChange={setAnnotations}
                            onSelectAnnotation={setSelectedId}
                            selectedId={selectedId}
                            tool={tool}
                        />
                    )}
                </div>

                {/* Properties Sidebar */}
                <div className="w-72 border-l border-gray-800 bg-gray-900 flex flex-col">
                    <div className="p-4 border-b border-gray-800">
                        <h3 className="text-xs font-bold text-gray-500 uppercase mb-4">Properties</h3>
                        {selectedAnnotation ? (
                            <div className="space-y-4">
                                <div>
                                    <label className="text-xs text-gray-400 block mb-1">Class Label</label>
                                    <input
                                        list="classes"
                                        type="text"
                                        value={selectedAnnotation.label}
                                        onChange={(e) => handleLabelChange(e.target.value)}
                                        onBlur={(e) => handleLabelBlur(e.target.value)}
                                        className="w-full bg-gray-800 border border-gray-700 rounded px-2 py-1 text-sm focus:border-blue-500 outline-none"
                                    />
                                    <datalist id="classes">
                                        {projectClasses.map(cls => (
                                            <option key={cls} value={cls} />
                                        ))}
                                    </datalist>
                                </div>
                                <div className="grid grid-cols-2 gap-2 text-xs text-gray-400">
                                    <div>X: {Math.round(selectedAnnotation.x)}</div>
                                    <div>Y: {Math.round(selectedAnnotation.y)}</div>
                                    <div>W: {Math.round(selectedAnnotation.width)}</div>
                                    <div>H: {Math.round(selectedAnnotation.height)}</div>
                                </div>
                                <button
                                    onClick={handleDelete}
                                    className="w-full bg-red-900/50 text-red-400 border border-red-900 hover:bg-red-900 p-2 rounded text-xs transition-colors"
                                >
                                    Delete Object
                                </button>
                            </div>
                        ) : (
                            <div className="text-gray-600 text-sm text-center py-4">
                                Select an object to edit
                            </div>
                        )}
                    </div>

                    <div className="p-4 flex-1 overflow-y-auto">
                        <h3 className="text-xs font-bold text-gray-500 uppercase mb-4">Objects List ({annotations.length})</h3>
                        <div className="space-y-2">
                            {annotations.map((ann, idx) => (
                                <div
                                    key={ann.id}
                                    onClick={() => {
                                        setSelectedId(ann.id);
                                        setTool("select");
                                    }}
                                    className={`p-2 rounded cursor-pointer text-xs flex justify-between items-center border ${ann.id === selectedId ? "bg-blue-900/30 border-blue-500" : "bg-gray-800 border-transparent hover:border-gray-600"
                                        }`}
                                >
                                    <span className="font-medium truncate">{ann.label}</span>
                                    <span className="text-gray-500">#{idx + 1}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}
